# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GourmetApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GourmetApp
  pod 'SwiftLint'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'R.swift', '~> 4.0.0'
  pod 'RealmSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'

  target 'GourmetAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'Mockingjay'
  end

end
